import aq.paqj.common.math.MyMath;
import org.apache.commons.math3.complex.Complex;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Complex re = MyMath.add(1.0, 2.0);
        System.out.println(re);

//        re = MyMath.sub(1.0, 2.0);
//        System.out.println(re);
    }
}
